### ISSUE TITLE
Streamlink optional ? Youtube h264/AAC support?

### ISSUE THREAD

**Issue by siliconhippy** [cabernetwork/cabernet#119]
Hi !

I was led to the TVHeadend forum by Bing Skype Chat  (AI bot) when I asked about my Youtube streaming problem with Jellyfin: youtube links don't stream in the client (Chrome browser.)

One solution is to configure streamlink appends in the original m3u playlist file entries to force h264/AAC (nistead of VP8/9) output to TVH so, hopefully, when Jellyfin Live TV receives the TVH output, the youtube links do play in the client browser. However I also want to stream Plex, Pluto and Tubi etc in the same or additional m3u playlist file(s) ...

So: Can the streamlink option work with Cabernet (in Linux Ubuntu instance) to stream all Youtube, Plex, Pluto etc channels to Jellyfin chrome client correctly without jellyfin or tvheadend transcoding, or channels start delays?

Would both live and VoD TV Channels be supported?

**Comment by rocky4546** [comment]
To answer some of your questions: 

Can the streamlink option work with Cabernet?  Cabernet can use streamlink; however, it currently does not have any ability to add arguments to the streamlink call.

Can Cabernet stream YouTube, Plex and Pluto?  Streamlink is NOT required to stream channels from providers.  In fact, the best stream type to use is internalproxy.  Streamlink does not work with PlutoTV, but internalproxy does.  Plex is available via a m3u file.  I have not heard anyone connecting to youtube with Cabernet, but if you have a m3u file, it probably will.  The M3U Plugin can be used to play most M3U files.

Can you use Jellyfin or TVHeadend without transcoding? Well, yes and no.  First, to record a channel does not take transcoding. Next, I have Jellyfin set to Direct Stream from the client.  Recordings from channels are all going to be a TS (Video Transport Stream) format since these are all HLS streams. This format is almost what Jellyfin needs to transmit.  All it does is add a MPEG wrapper and sends it, so the processing is minimal.  As for channel start delays.  The only delays Cabernet has is the ones from the providers.  It is up to the provider to provide a fast and effective stream, but expect some delays because these are free channels.

Does Cabernet support both VOD and Live? Yes, you can either inform Cabernet that the channel is VOD or the provider can let Cabernet know.  (XUMO is an example of VOD channels).  When a VOD channel is detected, Cabernet will make a few changes to the downloads making it faster and with less dropped packets.  I can download a 2 hour VOD movie from XUMO in about 3 minutes.

**Comment by siliconhippy** [comment]
Ok 👌 thanks.

Is internalproxy a streamlink parameter or a Cabernet one ?

**Comment by rocky4546** [comment]
They are carbernet stream types.  There are 4 stream types streamlink and internalproxy are two of them.
