### ISSUE TITLE
Integration with Plex

### ISSUE THREAD

**Issue by joelstitch** [cabernetwork/cabernet#13]
Hello, I am new to Cabernet since I just discovered it in the process of searching how to watch USTVGO with Plex. I was able to install and run Cabernet on my Synology NAS thats also running Plex. I am unsure how to get it working with Plex. In Cabernet settings I enabled USTVGO. In Plex Settings > Manage > Live TV & DVR I add http://172.17.0.2:6077 and it recognizes it but when I continue and scan for channels I get this message 

`No channels found. Make sure your device has a signal from your antenna and try scanning again.`

https://imgur.com/a/zxMq2QJ

```
[plutotv_default]
label = PlutoTV Instance
enabled = True

[loggers]
keys = root

[logger_root]
level = DEBUG
handlers = loghandler

[handlers]
keys = loghandler, filehandler

[formatters]
keys = extend,simple

[handler_filehandler]
enabled = False
level = INFO
formatter = extend
class = lib.common.log_handlers.MPRotatingFileHandler
args = (os.getenv('LOGS_DIR','data/logs')+'/cabernet.log', 'a', 10000000, 10)

[handler_loghandler]
enabled = True
level = WARNING
class = StreamHandler
formatter = extend
args = (sys.stdout,)

[formatter_extend]
format = %(asctime)s-%(levelname)s:%(module)s %(message)s

[formatter_simple]
format = %(levelname)s:%(module)s %(message)s

[main]
uuid = D8D2A2C0-C948-11EC-B01F-0242AC110002

[hdhomerun]
hdhr_id = 105346B6

[ustvgo]
enabled = True

[m3u]
enabled = True
```

**Comment by rocky4546** [comment]
In order to use any plugin, it must be instantiated with an instance/instance name.  Think of a plugin as a class and the instance is the object created from the class.  For USTVGO, you have no instance listed, so no data would be collected.   You can look at the channel list in Cabernet and see whether channels are listed. Why plutotv does not have channels is a different issue and would need to look into the logs to see what the issue is.
