### ISSUE TITLE
M3U8_Queue Unknown Channel - When Connecting to DaddyLive

### ISSUE THREAD

**Issue by alecdog08** [cabernetwork/cabernet#159]
Hello! Ultra noob here, having some trouble with connecting to the DaddyLive plugin.
The goal is to run these channels through Jellyfin, which I was successful with XUMO, and the Plex Channels, but I'm getting an error whenever I attempt to open a stream. I've attempted from both VLC and Jellyfin. 
In Terminal, I see:
![IMG_3227](https://github.com/user-attachments/assets/086d8cb9-dbdc-410a-bcad-ddf816c30ff3)

While in the Cabernet UI, I see this on the Tuner (The channel is different from the one above, as the pictures were taken at different times, same this happens though.)  :
![cabernet](https://github.com/user-attachments/assets/a1ad6ee5-7365-4037-ace9-0ff20c5e3650)

Would definitely appreciate the help! The application has been working well so far with other providers.
Let me know if there's anything else I need to provide.
Cheers.

**Comment by purplescorpion1** [comment]
Posted in wrong repo did you check dlhd website because there were a number of channels that failed to load due to a manifest error. They have now been fixed
Issues for dlhd are
https://github.com/cabernetwork/provider_video_daddylive

Also make sure you are using the channel list from 
https://github.com/cabernetwork/provider_video_daddylive/issues/22

**Comment by rocky4546** [comment]
Duplicate https://github.com/cabernetwork/provider_video_daddylive/issues/22
