### ISSUE TITLE
Question regarding EPG

### ISSUE THREAD

**Issue by ovargasp** [cabernetwork/cabernet#169]
As I said this is not an issue but a question, my iptv provider changed the EGP from 7 days to 30 days, that causes that now my clients when connect to cabernet, timeout while downloading the EGP info (I think)... cabernet log has this: "2024-11-06 13:11:48,608-INFO:epg2xml Connection dropped by client [Errno 32] Broken pipe". I suppose it's timing out, because I can't get logs out of the androidtv app. So my question is, is it possible to limit the number EPG of days cabernet sends to a client?? I can see the text files cabernet generates for the provider, one per day, so I'm wondering if that's something you can configure but I haven't found yet... 

thanks

**Comment by rocky4546** [comment]
First, no you cannot filter out EPG data using Cabernet.  What you import is what you get.  There are two methods you can use to stop the error.  First, I use a cronjob to grab the xmltv.xml file from Cabernet and then import that file into the media server.  The timeout that occurs is caused by the time it takes Cabernet to serve up the data, so grabbing the file from your system is 10 times faster. Next, you can run a script that strips some of the data from the xml file, if the file is still too big to ingest.  I don't have this problem, but you can do that.

**Comment by ovargasp** [comment]
I see, thanks for the pointers, can you tell me where is the xmltv.xml stored in the cabernet file system??, I forgot to metion that I'm using the docker version... Another question... If I delete some of the text files from the conf/db/epg location let's say it has files from 2024/11/06 through 2024/12/06. If I delete files from 2024/11/10 forward every time that I syncronize the EPG will it reduce the xmltv file, or will it break the cabernet db?? I can create a cronjob to do that as well an reduce the size of the file artificially.

**Comment by rocky4546** [comment]
http://ipaddress:6077/plugin/instance/xmltv.xml

**Comment by ovargasp** [comment]
Thanks @rocky4546. So I should create the file locally using the web server (http://localhost:6077/plugin/instance/xmltv.xml) and then copy it to the headend.

**Comment by rocky4546** [comment]
One last note.  The TVH grabber files are scripts and normally will contain the timeout causing the issue you listed in the first post.  Extending the timeout is something you might consider, but I would still run a cronjob so the grabber file can ingest directly from the filesystem.
