### ISSUE TITLE
Issue: Certain channels get re-enabled on restart + question

### ISSUE THREAD

**Issue by Aetherinox** [cabernetwork/cabernet#181]
One issue / two question.

I've noticed that there are sports channels I don't want that I want disabled.

![vTQHGNfiVj](https://github.com/user-attachments/assets/e148dd49-133f-4930-96d9-28568208f5e2)

I untick them, save, and then say 20 minutes later, give the docker container a restart, and suddenly, they are re-enabled again. But the weird thing is that it's only those sports channels. Others that I have disabled in the past seem to stay disabled.

And first question is regarding the database management tab.

![alFCIQ1JNO](https://github.com/user-attachments/assets/d06a22ce-1f92-4a7d-ad94-e3172bb2614a)

When clicking the button **Reset**, it says that on next request, the data will be re-fetched, but doesn't clarify how to initiate this. Does it re-pull the data when the container is restarted? Or does it re-pull when say a pull request is done by Jellyfin over to the Cabernet application.
 
When I click the reset button for Channels, should I do a restart of the container?

And should I click both the reset buttons for EPG and channels at the same time and do a restart, or should I click the channels reset first, and then restart, and then click the EPG reset, and do a 2nd restart. Because this container seems to only do things when a restart occurs.

Reason I ask this is because if I edit a playlist image / icon, and restart / refetch, the image in Jellyfin doesn't update. Even with a hard refresh on the browser page.

Last question, the group / category.

![XvXulDZ1WO](https://github.com/user-attachments/assets/1e0b96f5-a902-4770-b772-f892e4f1ded5)

Am I doing this correct? I notice that no channels show under Movies, but I've set the group

![eC31XekfTy](https://github.com/user-attachments/assets/7c107260-5187-48da-ab5d-8b647f658140)

**Comment by ovargasp** [comment]
Those aren't exactly channels, those are events and depending on your source they may or may not have a proper channelID so it will be hard to disable them, I use m3u8 sources and the m3u plugin, so to deal with those events I use the M3U Filter option from the Stream Provider configuration... I don't use the other plugins so I don't know if there is a filtering option but you may want to look into that.

About the Reset channel data, I don't use that, usually the scheduler takes care of it, updates all channel/epg info the UI it says that reset channel data will force pull new data, so if it works as the scheduler you don't have to restart the container, by doing that you're most likely running the scheduler for channel/epg sources that have a pull task on start/restart. You can use the option Restart in the Scheduled Tasks/Applications that does the same without you having to restart the container every time. In fact I hardly restart the container.

Your third question about groups, in my experience with the m3u plugin, cabernet adds the pluggin name to the group-title so what you're showing, to my client I have to look for group "M3U|movies" not movies because cabernet plugin requires that as the group name.

**Comment by rocky4546** [comment]
As for disabling channels, the data is found in the data/db folder.  All data for the channel editor are found together, so any change to one channel should be reflexive of the other channels.  I would look at what you are doing since it seems to be an environmental issue.
