### ISSUE TITLE
every update breaks cabernet

### ISSUE THREAD

**Issue by merrychrishna** [cabernetwork/cabernet#46]
i should tell you every update you push breaks my cabernet and i have to do a fresh install.

**Comment by rocky4546** [comment]
Trying to see what is happening.  I did a fresh install on windows and then an upgrade.  The default location for the logs (at least for me is
C:\Users\user\AppData\Local\Temp\cabernet
During the upgrade the error.log contained the following exception:
Traceback (most recent call last):
  File "D:\Program Files\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "D:\Program Files\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Program Files\cabernet\lib\updater\updater.py", line 144, in upgrade_app
    if not app.upgrade_app(STATUS):
  File "D:\Program Files\cabernet\lib\updater\cabernet.py", line 188, in upgrade_app
    if b.delete_code() is None:
  File "D:\Program Files\cabernet\lib\db\datamgmt\backups.py", line 160, in delete_code
PermissionError: [WinError 5] Access is denied: 'D:\\Program Files\\cabernet\\lib\\tvheadend\\service\\Windows\\nssm.exe'

Not sure why that is happening, but can you determine if your log files have a similar exception.  Will look into this one.

**Comment by rocky4546** [comment]
I think I know why this is happening. MS is always trying to make sure exe files are protected.  This one is used manipulate windows services.  It is possible that MS has it locked and unable to remove.  Since this file is very rare to be updated, I am going to ignore the error and do the upgrade except that file. I will have warning that is happening, but if the file has not changed, it should have no effect.

**Comment by merrychrishna** [comment]
ok awesome. well everytime cabernet breaks and i uninstall it i lose the log files but next time ill try to get the logs before i uninstall it.  also, can you remind me where the location of the log files are located?

also, i noticed since cabernet is installed to c:program files, when i make a batch file to run the startupt python tvheadend command to run cabernet, i always need to run the batch file as administrator or i get permission erros and cabernet doesnt start up. so could you possibly make cabernet into an exe file that prompts for uac or maybe make it so i dont need to run as admin at all?

**Comment by rocky4546** [comment]
Figured out more.  You see, the nssm.exe (used by the Service) is locked because Cabernet has to be up in order to do the upgrade.  During the upgrade it tries to remove the nssm.exe file that is part of Cabernet and MS says its locked, so unable to remove it.  This all makes sense.  I am working to get a number of things addressed as part of windows install/uninstall/upgrade.  Hopefully, things will run smoother once done.

To answer your question on admin priv.  I have had to deal with this in the past. The reason you need admin priv is because you need admin priv to be able to write to the data folder. Also, you can use the -c option to define the location of the data folder (see the service item for the option parameter it uses).  If you are running it as yourself, you can define it without the -c option (but Windows won't like it because it will try to create a data folder in the Program Files/cabernet area... giving you the permission denied error.  I have my data folder off in a E:\TEMP\cabernet area that is not deleted and writeable, so no issues.

**Comment by merrychrishna** [comment]
ok i installed cabernet on another drive which is what i think you were saying to do because -c was only working for the config.ini but there was still permission errors for the logs foldder because it was still looking for the logs on the c drive. so installing cabernet to my z drive is not requiring permissions.

**Comment by rocky4546** [comment]
Not really, but ok.  The concept is windows installs programs into a protected area.  The data files and logs need to be somewhere else per MS.  So I just picked a spot and said that is where the data files are located. This has nothing to do with where you install cabernet.  Yes, the -c option points to the config.ini.  That config file has two lines in it:
`[paths]

data_dir = E:\Temp\cabernet
`
This tells Cabernet where to find the data folder.  In my case the data folder is called cabernet in E:\Temp.
Glad you were able to get it running without permission issues.  

Still working on getting all the install issues resolved...

**Comment by merrychrishna** [comment]
oh ok. sweet.

**Comment by rocky4546** [comment]
So version 06 seems to work for me.  It now keeps the config.ini settings and does not delete them, it also keeps the ffmpeg install and the uninstall executable and ... a few other changes.

Now this fix is like the chicken and the egg.  It is possible you will need to install this version instead of upgrading it in order to get the fixes that fix the upgrade capability.  If you want to test it, it pretty simple... After installing .06

1. Go to cabernet/lib/common/utils.py and edit it.
2. Change line 30 to version 0.9.10.02 (or something less than 06...)
3. Restart Cabernet.  As part of the restart it will check for the upgrade and see 06 is available
4. Now you can run the upgrade and see if it will work as you would expect.  Let me know the results.

**Comment by merrychrishna** [comment]
Sweet that worked. Uninstalled the old version. Installed 06 pasted in my
backup data folder. Edited the utils.py and restarted. Then did the upgrade
and nothing broke this time. Nice work.
