### ISSUE TITLE
How does cabernet sync m3u file updates

### ISSUE THREAD

**Issue by Shazib** [cabernetwork/cabernet#82]
My stream urls have a token in them http://blahblah.blah/TOKEN/streamid/

These change when the m3u file refreshes. 

How does cabernet sync the updates with custom changes? will it think these are new channels or does ot match up on the EXTINF information? 

Only, i made some changes and then they disappeared after i forced a refresh.

Thanks

**Comment by rocky4546** [comment]
There is little info you have provided in order to answer your question.
1) What plugin are you talking about?
2) What stream url are you talking about?  Is it the one in the M3U file or something the M3U stream pulls in from that M3U URL?

If you are saying the M3U file changes and you want to pull the new M3U file, often.  The simple answer is to add a scheduler event that meets your update requirement and to change the minimum channel update rate to under that time.

**Comment by Shazib** [comment]
Hi,

1. Using the m3u plugin
2. The url to the m3u file itself. 

This file appears to change on a schedule i do not know, out of my control, and it changes in such a way that the urls for the streams all change. 

My query is that if the urls per-stream change, will cabernet be able to cope with this, or will it view them as new channels?

How does it determine what is a 'new' channel in the list vs something it already had?

m3u4u for example, thinks that there is an entirely new set of channels so and custom configuration such as enabled/disabled is lost.

Thanks

**Comment by rocky4546** [comment]
First, if the m3u URL changes, then that is a big issue since the M3U plugin assume the M3U URL is static.  You can write a plugin to handle such issues, but the M3U plugin assume the m3u setting is static.

If you have the correct m3u URL, then when it pulls things down, it will determine channel uniqueness based on the channel UID in the m3u file.  If that stays the same, then the channel will not change.  If the UID is not present, then I believe it will use the channel name to determine uniqueness.

**Comment by Shazib** [comment]
Thanks for the info. My url does indeed change so i will just proxy this somehow. 
I do not have UID but the name does not change so i should be ok in this case.

Thanks
