### ISSUE TITLE
Edit Channel Numbers

### ISSUE THREAD

**Issue by DevanDrake99** [cabernetwork/cabernet#93]
I tried to edit channel numbers to the ones I like, but Jellyfin and Kodi is only going by alphabetical order rather than my customized channel numbers.

**Comment by DevanDrake99** [comment]
Kodi isn't doing a custom channel order. And then all of the channels are 0s instead of the specific channel.

**Comment by rocky4546** [comment]
Although, I have found an issue with the code and will fix it, the issues you are having are with apps external to Cabernet.

**Comment by DevanDrake99** [comment]
Some channels ended up playing incorrect ones, such as foreign sports channels instead of the channels I wanted.

**Comment by rocky4546** [comment]
Channel number update in 0.9.13.09.  This fix stops users from cause their own issue by having the Starting Ch Number set while trying to change the channels in the channel editor manually.

If you read #78 and changed the "Use Channel # for Channel ID" to true, it states you can cause your own issues by changing channel numbers.  After a while, the clients will resync to the new numbers, but in the meantime, issues like the ones posted are expected.

This issue is fixed and closed.
